development:
  adapter: mysql2
  database: knewp_proxy_production
  pool: 5
  host: 107.170.214.133
  username: knewp
  password: knewp

production:
  adapter: mysql2
  database: knewp_proxy_production
  host: localhost
  pool: 5
  username: knewp
  password: knewp

nagios_development:
  adapter: mysql2
  database: nagios
  host: 107.170.214.133
  pool: 5
  username: nagios
  password: nagios

nagios_production:
  adapter: mysql2
  database: nagios
  host: localhost
  pool: 5
  username: nagios
  password: nagios